// questions-data.mjs — the one source of design/proposal/questions.md and
// design/proposal/review/index.html (Q1541, stage 6's second half).
// Markup in strings: *italic*, **bold**, ⟨code⟩. Shots: [today, proposed, caption];
// either side may be null. `c:` names shots/current/, `p:` shots/proposed/.

export const questions = [
  {
    title: 'Go ahead with phase two: rebuild every card from one shared description of its state',
    now: `Today each of about 40 kinds of card builds itself. Each one works out for itself whether the document is closed, who is looking, who chose a rule and what to draw, then writes its whole card. That is why the same fault keeps turning up somewhere new — a member reading *Set to undefined*, a closed document offering *Accept*, a 🗑️ with nothing to put back — and why every fix so far has covered one card.`,
    change: `One shell draws every card from one description of its state: what it is about, who is looking, where the document is in its life, what stands and who chose it, and what this reader may do now. A card can only be drawn from that description, so those faults cannot be written again. **Be clear about what the prototype you can click is:** it is not that. It takes the markup today's cards already write and *sorts* it into the new layout. It shows the look, and the checks pass against the sorter; the real build has to pass them again from nothing. Converting the 40 card bodies is most of the work (BUILD.md sizes the whole programme at 27–32 builder sessions and 10–11 QA rounds); the shell, the tokens and the checks are small beside it. And P10 — *nothing you are in the middle of is taken by the page updating* — is not built in the prototype at all (see 1541.18).`,
    buys: `Every class of fault the diagnosis counted (1,226 of 1,336 opened cards carried at least one) becomes either impossible to build or caught by a check that goes red. New cards are built by filling in one description, not by writing a card.`,
    costs: `Weeks of builder time and a QA round per card family. While a stage is open, other card work in the same six files waits (BUILD.md lists which).`,
    shots: [['title-settled-1600.png', 'title-settled-1600.png', 'The 🪶 card that started this, today and in the prototype']],
    options: [
      ['Yes — the staged build', 'BUILD.md\'s migration, one card family at a time, each family\'s checks becoming guards as it lands; the sorter is thrown away, never merged.'],
      ['Only the cheap half', 'Patch today\'s card builders until they pass the checks, with no shared description. Faster; the next new condition brings the faults back, because each card still works out its own state.'],
      ['Not now', 'Keep the proposal on its branch as a reference and go on fixing faults one card at a time.'],
    ],
  },
  {
    title: 'Make the ten principles the surface\'s standing rules',
    now: `SURFACE.md states its rules card by card (C1–C17, CP1–CP11, K1–K34 and more). It has no short list a reviewer can hold against a screenshot, and three of its rules contradict each other today: what a closed card's buttons are (K2 against CP9), whether a single-place draft has its own ✏️ (§9 against §9.1), and whether the tab you press moves (C1 against what every charter card does).`,
    change: `The ten principles (listed on the review page and in grammar.md §1) go into SURFACE's opening, each naming the automatic check that holds it. The card-by-card rows then state only what is particular to each card.`,
    buys: `A new card is judged against ten sentences, and each sentence has a check that turns red. The three contradictions go, because the answers below settle each of them.`,
    costs: `SURFACE's opening changes. P10 would enter as a rule the page does not yet keep, marked *not built* until the re-render stage.`,
    options: [
      ['Adopt all ten, with their checks', 'Into SURFACE\'s opening; P10 marked *not built* until BUILD.md\'s stage 9.'],
      ['A design guide only', 'Keep them in design/DECISIONS.md as guidance; SURFACE stays card by card.'],
      ['One by one', 'Adopt each principle only as the questions below that depend on it are answered.'],
    ],
  },
  {
    title: 'Every card starts with the line it opens in place of',
    now: `A card replaces the paragraph you pressed, but what stands at its top depends on the kind. A settings card has no head and repeats the rule as its first option — *The document is titled "…"* over a blue *Chosen by the Founder* pill. A charter card has a small grey *The clause as it stands* above the clause. The grants open with their own headings. And about 322 opened cards carry an empty 24 px box above everything.`,
    change: `Every card's first line is the paragraph it replaces, drawn by the same code that draws it in the document, word for word, exactly where it stood. What stands leaves the list of options, because it is the first line. Four stated exceptions: a **record** starts with the wording it recorded; a **patch** over several places starts with the place it is showing; a **gap** starts with *(no text here)*; and at the **birth**, before there is a title, 🪶 starts with the title box itself at title size. A rule's paragraph also carries a line about the Founder's powers; the card leaves that line to the ✒️ 🛡️ cards (1541.10).`,
    ruling: `SURFACE F15 and STYLE T3 — *"an option-block settings card carries no head … and a heading-over-text card — the grants and the gates — no title head (Q1151, Q1373)"* — and §9's blind-answer row (Q1175) and settled-record row (Q1186, Q1522). Each of these removed a head that *restated* the card. Your reading (Q1373): *no card carries a title*. The proposal keeps that: the first line is not a title, it is the line itself.`,
    buys: `Nothing is said twice. The empty head box goes; four ways of drawing a card's top become one; the *Set to undefined* kind of fault cannot happen, because the first line is the document's own rendering and cannot disagree with it.`,
    costs: `Every band card's first line changes. The grants and gates start with the line their tab hangs on (the Founded line, the Proposals preamble).`,
    shots: [['title-settled-1600.png', 'title-settled-1600.png', '🪶 settled'], ['chamber-settled-1600.png', 'chamber-settled-1600.png', '🌍 settled, the Founder'], ['grant-pen-settled-1600.png', 'grant-pen-settled-1600.png', 'the ✒️ grant']],
    options: [
      ['Take it, with the four exceptions', 'Every card, band and charter.'],
      ['Band cards only', 'Settings cards start with their rule; charter cards keep today\'s top.'],
      ['Keep today\'s rules', 'No head on settings cards; each kind keeps its own top.'],
    ],
  },
  {
    title: 'One place for labels: each block\'s label is its first line, and the card\'s own label sits above the first line without moving it',
    now: `An opened charter card has a small grey *The clause as it stands* above the clause, which is why the tab you pressed drops 33 px when the card opens (62–84 px on a record, 99 px on the closed page's backlog at 390). Block labels stand in four different places: *Proposed* above, beside or below its block, *Previous text* above and to the right, *What you proposed* at the block's foot. A record opens with a green *DECIDED · 7/14* row above the clause.`,
    change: `Every block's label is its first line. The card's own label — *Current text*, *Current rule*, or how a record ended (*Passed · Thursday, 24 September, 22:51*, in green) — sits in the space the card's box already takes above its first line. It is still read first, and it moves nothing: the clause lands exactly where the paragraph was, and so does the tab you pressed. One short vocabulary of labels (grammar.md §2.3a lists it: *Current text*, *Current rule*, *Proposed*, *What you proposed*, *Previous text*, *Rival · n%*, *Rejected proposal*, the outcome words, and a card's ask); a block with no button and no label cannot be built. The first version of the proposal put labels beside radios, which left cards with no radio unlabelled — the critique caught it, and this is the fix.`,
    ruling: `CLAUDE.md's glossary, *clause-head*: *"the clause at document size and colour under an eyebrow"*; SURFACE M19, *"its head is the eyebrow The gap as it stands"*; M12, *"a record's head stands a dateline row lower in its card (Q1524 (a))"*. Kept in substance: Q207 (a first-time reader must be told which paragraph is the current text) and Q1522 (a record says what it did first).`,
    buys: `*The tab you click does not move* becomes true on the charter, where it is false on every card today. Labels read one way everywhere. Records still lead with their outcome.`,
    costs: `*The clause as it stands* and *The gap as it stands* become *Current text*. A card packed tight under the line above it (📍 at the birth) has room for no label — it has no blocks there, so it needs none. The label costs 4 px in the band (1541.15).`,
    shots: [['quick-keys-charter-1600.png', 'quick-keys-charter-1600.png', 'a quick judgment'], ['race-purse-charter-1600.png', 'race-purse-charter-1600.png', 'rivals only'], ['race-claims-charter-1600.png', 'race-claims-charter-1600.png', 'a sealed record']],
    options: [
      ['The label slot, as built', 'Block labels on their first line; the card\'s label above the first line, moving nothing.'],
      ['Labels beside the radios', 'The first version: a card whose first line has no radio has no label (Q207 lost on rivals-only races, your own proposal and the deadlock).'],
      ['Today\'s placements', 'Keep the label above the clause and accept the 33–99 px drop.'],
      ['No labels', 'Position says it; Q207\'s first-time reader unanswered.'],
    ],
  },
  {
    title: 'Who chose a rule is a line of grey text, not a pressed blue button',
    now: `Under every settled rule a solid blue pill reads *Chosen by the Founder ✒️* or *Chosen by the membership* — drawn exactly like the option you just pressed, and in the same fill as OK. 490 of the opened cards carry one.`,
    change: `The same words, verbatim, as one grey line under the rule, with the moment: *Chosen by the membership · Sunday, 20 September, 11:12*. On a record the outcome stands in for it — *Passed* is the membership's choice and *Changed by the Founder* the Founder's — so a record does not print both.`,
    ruling: `SURFACE CP2: *"Provenance is a sanctioned third form, and the standing block always wears it (Q1167 (a), Q1176, Q1188 — Ed 2026-09-05)"*, and STYLE T48's second half. You have confirmed the pill three times. Q1188's reason — a reader should not have to infer who chose a rule from a missing label — is kept: every settled rule still says who chose it, in the same two phrases.`,
    buys: `A fact about the past stops looking like a button you can press, and stops sharing its drawing with OK. It gains its moment.`,
    costs: `It re-draws a ruling you have made three times.`,
    shots: [['chamber-settled-1600.png', 'chamber-settled-1600.png', '🌍 settled'], ['admission-settled-1600.png', 'admission-settled-1600.png', '🪪 settled'], ['rec_chamber_0-settled-1600.png', 'rec_chamber_0-settled-1600.png', 'a settled motion record']],
    options: [
      ['A grey line of text', 'T48\'s two labels verbatim, with the moment; the outcome word on records.'],
      ['Keep the pill', 'The pressed radio stays the drawing of who chose.'],
    ],
  },
  {
    title: 'On a locked or closed card, the settings options nobody can choose are not drawn — but proposals stay',
    now: `After 🍾 the 🎩 card shows both *The Founder is part of the membership* (marked Chosen) and *The Founder is not part of the membership* with a greyed radio. On a closed document every setting still shows its options with *Choose this* radios, and every race its *Prefer this* radios.`,
    change: `The proposal tells two kinds of block apart. A **settings option** exists to be chosen, so where this reader cannot choose, the unchosen options are not drawn: what stands is the first line, and who chose it the grey line under it. A **proposal, a rival, a record's field, or a race the clock cut off** is content, so it stays, labelled (*Proposed*, *Undecided when the document closed*), with no radio. (The first version dropped proposals too, and the closed deadlock lost its eight proposals; the revision put them back.)`,
    ruling: `SURFACE CP11: *"A block nobody may press keeps its words and greys its radio alone (reading 1193, 2026-09-05): a locked or unavailable option is read as often as a live one"*; §8's exception row, *"the hat's radios stay visible but disabled post-start"*.`,
    buys: `No radio anywhere that cannot be pressed. The closed page asks nothing and still shows everything it recorded.`,
    costs: `A locked 🎩 no longer shows the answer that was *not* chosen. Reading 1193's worry is met differently for the two kinds: a locked option was never something anybody could do; a proposal stays readable.`,
    shots: [['hat-settled-1600.png', 'hat-settled-1600.png', '🎩 after 🍾'], ['rate-closedband-1600.png', 'rate-closedband-1600.png', '⏱️ on the closed page'], ['race-sanctions-closed-1600.png', 'race-sanctions-closed-1600.png', 'the deadlock on the closed page']],
    options: [
      ['Take it', 'Unchosen settings options go where nobody can choose; proposals stay, labelled, with no radio.'],
      ['Keep greyed radios on settings', 'CP11 for settings options; radios removed only from proposals on the closed page.'],
      ['Keep today\'s', 'Greyed and live-looking radios as now.'],
    ],
  },
  {
    title: 'At the close, 🥂\'s signature also counts as every OK you still owed',
    now: `If a record, a park or a news card still owed you an OK when the clock closed the document, it keeps an OK button on the closed page (in the fixture: *knives*, *claims*, *Nomination*, *Locking Up*, *Calling a Meeting*) — although the module refuses an OK after the close.`,
    change: `🥂 is the closed page's one act. Its OK signs the document and, in the same press, acknowledges every OK still owed; those rail entries leave with the signature.`,
    buys: `The closed page has one act, as the proposal's closed-document principle says, and no button that the host would refuse.`,
    costs: `A change in the module (⟨packages/constitution⟩) so that the one press answers the owed set, and a full deploy rather than a surface-only one. Not built in the prototype: its cards simply draw no OK, and its rail is today's, so an owed entry still stands there until 🥂.`,
    shots: [['race-claims-closed-1600.png', 'race-claims-closed-1600.png', 'an unread record on the closed page'], ['closing-closedband-1600.png', 'closing-closedband-1600.png', '🥂']],
    options: [
      ['🥂 discharges them', 'One press signs and acknowledges; module change in BUILD.md stage 7.'],
      ['Each keeps its OK', 'No module change; the closed page offers acts besides 🥂 (and the host must accept them).'],
      ['Dropped at the close', 'What was owed is simply no longer owed once the document closes; no OK, no signature link.'],
    ],
  },
  {
    title: 'A card that asks nothing has no buttons; you close it with its tab, a click outside, or Escape',
    now: `A card with nothing left to do shows a lone OK that only closes it (an accepted grant, a settled 🎩, a settled 🍾, a stranger's read-only card), or, on a closed document, a lone 🗑️. SURFACE says both things: CP9 — never 🗑️ alone, show a close-only OK — and K2 — on a closed document, 🗑️ alone. The page follows K2 on 80 cards.`,
    change: `No button row at all. OK appears only when something is owed. You close the card by pressing its tab again, clicking anywhere outside it, or pressing Escape.`,
    ruling: `SURFACE CP9 (reading 1190): *"the OK being the reader's way to say they are done with a card that asks nothing"*; §9.1's OK row; K2.`,
    buys: `OK means one thing — *I have seen this, and I owed it*. The K2/CP9 contradiction and the held backlog item (*🗑️ alone against §9.1's close-only OK*) both go.`,
    costs: `A read-only card has no button. On a phone the way out is tapping the 34 px tab at the screen's edge or tapping elsewhere; BUILD.md measures that exit before this lands.`,
    shots: [['grant-pen-settled-1600.png', 'grant-pen-settled-1600.png', 'the ✒️ grant, accepted'], ['begin-settled-1600.png', 'begin-settled-1600.png', '🍾 settled'], ['hat-settled-1600.png', 'hat-settled-1600.png', '🎩 settled']],
    options: [
      ['No row; tab, outside or Escape', 'OK only while owed.'],
      ['No row, plus a quiet ×', 'A small close mark in one fixed corner of every card: easy to find, but furniture on every card and a second way of saying what the tab says.'],
      ['Keep the close-only OK', 'CP9 as it stands; K2 amended to match.'],
    ],
  },
  {
    title: '🗑️ appears only when there is something of yours to remove, and withdrawing says *Withdraw*',
    now: `🗑️ sits at the left of nearly every card, *always live*. On 388 opened cards it offers to *Put it back as it stands* with nothing to put back; on 👑 and the park it only closes the card; on your own proposal it is the only control, withdraws the proposal irreversibly, and says so only in its tooltip.`,
    change: `🗑️ is drawn exactly when there is something unsent here that no other control undoes (something typed, uploaded or toggled), or something you sent that can still be withdrawn. A choice among options that include Indifferent needs no bin, since choosing another undoes it — the reason behind Q1500, applied to every card rather than listed by kind. Withdrawing reads *🗑️ Withdraw*, because it is irreversible and a bare bin was read as *skip* (Q1500).`,
    ruling: `SURFACE C4, *"🗑️ at the left, always live"*; CP7; §9.1's 🗑️ row; CP5 (*"🗑️ at the left closes the card, the question kept pending"* on 👑); §9's park row.`,
    buys: `🗑️ has one meaning — remove what is yours — instead of four.`,
    costs: `The bin comes and goes as you start and clear a draft, so the left end of the row is sometimes empty (the buttons on the right do not move).`,
    shots: [['chamber-settled-1600.png', 'chamber-settled-1600.png', 'a settled rule: no bin until you type'], ['mine-guests-wording-charter-1600.png', 'mine-guests-wording-charter-1600.png', 'your own proposal: *Withdraw*'], ['mo_mo-3-settled-1600.png', 'mo_mo-3-settled-1600.png', 'the 👑 question']],
    options: [
      ['Bin only with a job; *Withdraw* in words', 'As built.'],
      ['Bin only with a job; withdraw a bare glyph', 'Same rule, no word on the withdraw.'],
      ['Keep the bin on every card', 'C4 as it stands.'],
    ],
  },
  {
    title: 'A settings card starts with the rule alone; the Founder\'s powers line belongs to the ✒️ 🛡️ cards',
    now: `In the document a rule reads as two lines: the rule, then *The Founder may amend this at will, and refuse proposals that the membership pass.* Today's opened card already drops the second line — your ruling of 2026-09-03, in the code: *the document keeps the powers; the card drops them*. But STYLE §3 still says *the opened card's head shows the same two lines*.`,
    change: `The proposal follows your 2026-09-03 ruling (its first version had quietly overridden it; the critique caught that). STYLE §3's sentence is amended to match. Each power card starts with its own clause of that line (1541.11).`,
    buys: `The first line of a settings card states one fact, and the powers are stated once, on their own cards.`,
    costs: `A STYLE amendment.`,
    shots: [['title-settled-1600.png', 'title-settled-1600.png', '🪶 settled'], ['chamber-settled-1600.png', 'chamber-settled-1600.png', '🌍 settled']],
    options: [
      ['Drop the powers line; amend STYLE §3', 'Your 2026-09-03 ruling governs; STYLE catches up.'],
      ['Show both lines, as STYLE §3 says', 'The first line then states two facts, and the ✒️ 🛡️ cards repeat the second.'],
    ],
  },
  {
    title: 'A power card starts with that power\'s own clause, says who holds it, and offers the other state',
    now: `Pressing ✒️ under ⏱️ opens two options: *The Founder may amend the proposal rate at will* (marked Chosen) and *The Founder may not amend the proposal rate at will*. Before 🍾 they are two equal blocks.`,
    change: `The first line is the power's own clause (*The Founder may amend this at will.*); the label above it is the card's question (*Can the Founder Make Amendments at Will?*); the grey line says who holds the power (*Kept by the Founder at the start · ‹when›*); the one block is the other state. On a closed document the clause turns to the past: *Until the document closed, the Founder could amend this at will.*`,
    ruling: `SURFACE K4: *"on a power card it stays, marked Chosen, because a two-state toggle needs its other half"*; §9's power-cards row, *"before 🍾 two proposal blocks"*.`,
    buys: `A power card is built like every other rule card; K4 needs no exception, and Q1430's doubled sentence cannot come back.`,
    costs: `Before 🍾 the pair reads as first line plus one block rather than two equal blocks.`,
    shots: [['pw_u_title-settled-1600.png', 'pw_u_title-settled-1600.png', '✒️ on 🪶'], ['pw_u_title-closedband-1600.png', 'pw_u_title-closedband-1600.png', 'the same, closed']],
    options: [
      ['Own clause, holder, the other state', 'As built.'],
      ['Two equal blocks', 'K4 as it stands.'],
    ],
  },
  {
    title: 'A card that asks you something says what it asks, as its label',
    now: `✋ 🖼️ 📧 and 🌂 keep a title (*Choose Your Name*) above your row. The grants, gates, 🍾, 🥂 and the power cards have none, or a different form.`,
    change: `Every card that is an act or a question — ✋ 🖼️ 📧, 🌂, 🥂, 🍾, the grants, the power cards, 🎩 while it is asked, 👑 — carries its ask as the small label above its first line, and its first line is the place (your row, the Founded line). Cards about a place (a clause, a rule) carry *Current text* or *Current rule* instead. The first version dropped the titles altogether; 🌂, the one card whose act cannot be undone, then named no act, so the revision put them back in this form.`,
    ruling: `STYLE T3 and SURFACE F15 keep the personal cards' title — kept. Extending the ask to the grants, 🍾, 🥂, the power cards, 🎩 and 👑 is new.`,
    buys: `Every card says what it is about or what it asks, in one place, drawn one way.`,
    costs: `The ask is small upper-case type. At 390 a long ask is cut with an ellipsis (*Can the Founder Make Amendments at W…*), its full words on the power card's first line. One note stays amber from the mockups: 🖼️ shows your initials twice, because the *Anonymous* option shows what choosing it draws.`,
    shots: [['myname-founding-1600.png', 'myname-founding-1600.png', '✋'], ['leave-settled-1600.png', 'leave-settled-1600.png', '🌂'], ['grant-voice-founding-1600.png', 'grant-voice-founding-1600.png', 'the 🏛️ grant']],
    options: [
      ['Every act or question card', 'As built.'],
      ['Only the cards that keep a title today', '✋ 🖼️ 📧 🌂; the grants and the rest carry no ask.'],
      ['No ask label', 'The first version; 🌂 names no act.'],
    ],
  },
  {
    title: 'Each drawing means one thing: ✓ is never green, a chosen option is a dot, a vote on changed wording is a sentence',
    now: `SURFACE §9.1 calls ✓ *"the one solid green on a card"* and also says it *"lights on --primary when armed"*; the recorded ✓ on a judged ⏳ card is green-tinted. A chosen option is a filled blue pill — the same fill as OK and as the provenance pill. A vote about wording that has since changed shows as a pressed *Preferred*.`,
    change: `Green means *decided* and stays on marks and on the record's passed highlight — never on a button. ✓ is drawn like every other glyph button (flat, lifted when armed). A chosen option is a white pill with a filled dot and blue words; solid blue is OK or Accept, while owed, and nothing else. A vote on wording that has changed is a sentence: *You preferred this before it changed*.`,
    ruling: `SURFACE §9.1's ✓ row (which contradicts itself).`,
    buys: `Nothing that already happened looks pressable, and no two different things share a drawing. The 👑 Text question's solid green ✒️ (plain bug 8) has nothing left to imitate.`,
    costs: `The ✓ is less emphatic, and every card's selected option looks quieter than today's filled pill.`,
    shots: [['quick-guests-count-charter-1600.png', 'quick-guests-count-charter-1600.png', 'a judged ⏳ pair'], ['quick-keys-charter-1600.png', 'quick-keys-charter-1600.png', 'a quick judgment, choosing']],
    options: [
      ['All three', '✓ flat, chosen as a dot, a changed vote as a sentence.'],
      ['✓ only', '✓ loses its green; the filled pill stays for a chosen option.'],
      ['Keep today\'s', '—'],
    ],
  },
  {
    title: 'The *Set to …* and *Set by …* lines go from every card',
    now: `A member reading a rule may see it three times — the rule, *Set to Anyone with the link*, and a change line — plus *Set by the founder when the document was made.* or *Decided by the members.* That second reader of the same facts is what printed *Set to undefined* (1541.29) and named two different choosers on one card (1541.31).`,
    change: `The rule once (the first line), who chose it and when once (the grey line), and what changing it takes stays in the document's own powers line.`,
    ruling: `SURFACE §9's watching row, *"the lockline and the value line only (Q1176)"*; STYLE T21's lockline example.`,
    buys: `One home for each fact; the two plain bugs above cannot recur. This also answers a held backlog item (*Set to / Set by on every read-only setting card*).`,
    costs: `The wording T21 protected, which the paragraph states anyway.`,
    shots: [['chamber-seat_1-1600.png', 'chamber-seat_1-1600.png', '🌍 read by a member'], ['chamber-live_constitution_m-1-1600.png', null, 'today on a live document: *Set to undefined*']],
    options: [
      ['Remove them', 'As built.'],
      ['Keep them, read from one place', 'Fix the two bugs but keep the lines.'],
    ],
  },
  {
    title: 'The band\'s subsection headings gain 4 px so a card\'s label fits above your row',
    now: `An opened card's box rises above its first line by its padding, over whatever is above it: at the birth 📍's card covers the descenders of 🪶's title, and 120 cards do this at 1600 (141 at 390).`,
    change: `A card rises only into clear space, never over ink. The card's label needs 13 px; the first row under a band subsection heading (✉️'s invitees, ❌, the members list that ✋ 🖼️ 📧 open on) has 11 px. To fit, each band subsection heading gains 4 px of space below it — always, closed page included.`,
    buys: `No card ever covers the line above it, and the label fits everywhere a label is needed.`,
    costs: `4 px of extra space under the band's subsection headings on every page, card open or not. The charter's headings do not change.`,
    shots: [['band-settled-1600.png', 'band-settled-1600.png', 'the band, no card open'], ['invite-settled-1600.png', 'invite-settled-1600.png', '✉️ opened under its heading']],
    options: [
      ['Accept the 4 px', 'As built.'],
      ['No label on those cards', 'They open under their heading with no label; the rail entry and the tab carry the ask.'],
      ['A smaller label there', 'Draw those labels below the type scale\'s smallest step (breaks the one-drawing rule).'],
    ],
  },
  {
    title: 'A card ends where its content ends, and a long tab strip hangs on down the margin',
    now: `An open card is at least as tall as its strip of tabs, so a card with little in it — a power card on a setting with many records — keeps 60–110 px of blank white under one line (30 cards at 1600).`,
    change: `The card ends at its content. Where the strip is longer, it hangs on down the tab margin beside what follows, and pushes what follows down only as far as a closed pile of tabs would.`,
    buys: `No padded cards; the tab you pressed still does not move.`,
    costs: `The strip visibly runs past the card's foot.`,
    shots: [['rate-closedband-1600.png', 'rate-closedband-1600.png', '⏱️, many records in the strip']],
    options: [
      ['The strip hangs on', 'As built.'],
      ['Fold the read part of the strip', 'Read records and laid-down powers fold into one pile tab inside the open strip: shorter strips, a second kind of pile, one more press to reach a record.'],
      ['Keep the floor', 'Today\'s padding.'],
    ],
  },
  {
    title: 'The floating 📝 may reach over the task rail\'s empty margin, but never over text',
    now: `At 1600 the floating 📝 — a 4.5 rem circle whose centre sits on the text sheet's right edge, as you ruled on 2026-09-24 — reaches over the task rail's left edge and covers the foot of its last entry (plain bug 6). Q1518 raised it below 1600; it is true at 1600 too.`,
    change: `The first version of the proposal moved the door inside the sheet, overruling you; the revision puts it back where you put it and states a rule instead: the floating layer may cross a zone's edge but never covers a line of text or a control. In the prototype at 1600 it crosses the sheet's edge and the rail's left margin, where no entry text stands — a slight overlap of rail entries' boxes, none of their words.`,
    buys: `Your placement kept, with a check that goes red the day it covers words.`,
    costs: `The door still overlaps the empty edge of a rail entry at some widths.`,
    shots: [['page-session-1600.png', 'page-session-1600.png', 'the session page at 1600']],
    options: [
      ['Keep your placement; never over text', 'A check (zone-overlap) guards it.'],
      ['Keep it, but shift it inward on narrower windows', 'Below a width where it would meet an entry, the door moves into the gap between sheet and rail.'],
      ['Inside the sheet', 'The first version; it stands in the text\'s right margin.'],
    ],
  },
  {
    title: 'Stop the page rebuilding what you are holding: keyed updates instead of wholesale redraws',
    now: `The page rebuilds each card wholesale on every action and on the 4-second poll. Each time that took something from under someone's hand — a caret, a half-typed date, a held button, a drag — it got its own guard flag. 22 of the 72 surface gotchas in CLAUDE.md are this.`,
    change: `Every part of a card gets a stable key, and an update patches only what changed, never replacing something you are holding (focus, a caret, a press, a drag, a typed value). This is principle 10; the prototype does not build it and no check measures it yet.`,
    buys: `The class of fault live rooms have taught hardest stops needing a flag per case.`,
    costs: `The riskiest stage of the build (BUILD.md stage 9); it touches how every card is drawn.`,
    options: [
      ['Its own stage, after the families', 'Keyed patching once every family is on the shell; a differential switch like the engine memo\'s audit mode.'],
      ['From the first stage', 'Every family lands already keyed: slower start, no second pass.'],
      ['Keep adding flags', 'No architecture change; the 23rd gotcha of this shape.'],
    ],
  },
  {
    title: 'Where the list of what you may do is worked out: in the page first, the host later',
    now: `Whether you may propose, judge, set, invite or accept is asked in about 27 separate places in the page, each card its own way, which is how a closed document came to offer *Accept*.`,
    change: `One function in the page answers it for every card, from the existing *may* checks, with *closed* inside it.`,
    buys: `The scattered tests go without a server change.`,
    costs: `The page could still offer something the host would refuse; only option (b) closes that.`,
    options: [
      ['In the page, one function', 'Now; the host version later, once the list\'s shape is proven.'],
      ['The host serves it', 'Each seat\'s allowed acts come with the view: stronger, a server change up front.'],
    ],
  },
  {
    title: 'On a phone, keep the tab margin but narrow it, so cards get more width',
    now: `At 390 every card stands 64 px in, with a 20 px right margin; the tab margin is kept (the tab is the only way into a card from the document). **Also:** your held backlog item *the separate cross-width design offer* — I read it as the earlier offer to design the phone layout separately. The proposal answers *one design, folded*: the phone has the same zones, and a card moves 0 px on open at both widths. If you meant something else, say so in the note.`,
    change: `The tab margin narrows to the tab's width plus 4 px and the card runs to 12 px from the glass. Not built in the prototype.`,
    buys: `More text width on a phone, and the tab still does not move on open.`,
    costs: `Needs building and measuring (the drawer walk, the narrow card audit).`,
    shots: [['quick-keys-charter-390.png', 'quick-keys-charter-390.png', 'a quick judgment at 390']],
    options: [
      ['Narrowed margin', 'As described; one design at both widths.'],
      ['Tabs along the card\'s top at 390', 'More width, but the tab moves on open at 390 and not at 1600.'],
      ['Leave 390 as it is', '—'],
    ],
  },
  {
    title: 'The *Why are you changing this?* box appears only once you change something',
    now: `Every settled rule card, ✉️ and the deadlock's desk show an empty reason box before anything has been chosen or typed.`,
    change: `The reason box appears with the first keystroke or pick, below the first line, so nothing above moves. A reason still rides every change (CP3).`,
    ruling: `SURFACE §9's composer row, which lists *the rationale lane* among the card's standing parts.`,
    buys: `No empty box asking why before there is a change.`,
    costs: `The card grows by one box at the first keystroke.`,
    shots: [['title-settled-1600.png', 'title-settled-1600.png', '🪶 settled'], ['race-sanctions-charter-1600.png', 'race-sanctions-charter-1600.png', 'the deadlock\'s desk']],
    options: [
      ['With the change', 'As built.'],
      ['Always shown', 'The composer row as it stands.'],
    ],
  },
  {
    title: 'In edit mode, a single-place draft has one ✏️ — the floating row\'s',
    now: `A draft at one place shows 🗑️ ✏️ twice: on its card and on the floating proposal row, which also overlaps the card's foot (plain bug 9). SURFACE says both: §9's editing row, *"none on the card — the ✏️ hold is the proposal-row's (Q1382)"*, and §9.1's ✏️ row, *"the same ✏️ drawn on a single-site card"* (Q1486 (E)).`,
    change: `The card carries no ✏️; the countdown to your next ✏️ stays on the proposal row's ✏️. The overlap is fixed either way (1541.39).`,
    buys: `One act, one button.`,
    costs: `None found.`,
    shots: [['editing-one-site-1600.png', null, 'a single-place draft, today']],
    options: [
      ['The row\'s ✏️ only', 'Q1382 wins; §9.1 amended.'],
      ['The card\'s ✏️ only', 'Q1486 (E) wins; the floating row hides for a single place.'],
    ],
  },
  {
    title: '🥂 states the closing moment once',
    now: `🥂 says the document *closed at 00:51* in its first line and *final as of 00:51* in a blue box beneath (plain bug 5).`,
    change: `The moment once, in the first line.`,
    ruling: `SURFACE §9's 🥂 row, *"final as of · the batch · your closing comment"*.`,
    buys: `One home for the fact.`,
    costs: `None.`,
    shots: [['closing-closedband-1600.png', 'closing-closedband-1600.png', '🥂']],
    options: [
      ['Once', 'As built.'],
      ['Keep both', '—'],
    ],
  },
  {
    title: 'The 🏛️ grant says *Accept 🏛️*, like the other three',
    now: `Three grants read *Accept ‹glyph›*; the 🏛️ grant reads *Activate 🏛️* (Q1502), matching its title *Activate Your Membership*.`,
    change: `*Accept 🏛️*, so one word means *I take this power* everywhere.`,
    buys: `One word per meaning.`,
    costs: `Q1502's match with the title goes.`,
    shots: [['grant-voice-founding-1600.png', 'grant-voice-founding-1600.png', 'the 🏛️ grant']],
    options: [
      ['Accept 🏛️', 'As built.'],
      ['Keep Activate 🏛️', 'Q1502.'],
    ],
  },
  {
    title: 'An empty invitations or removals list says so in a sentence, in the document and on the card',
    now: `The band shows *(no outstanding invitations)* and *(nobody proposed for removal)*; the cards say *Nobody has been invited yet.* and *Nobody is proposed for removal.*`,
    change: `Since a card's first line is the line itself, the two must match: the band says the sentences.`,
    buys: `The document speaks in sentences, and these two already passed STYLE.`,
    costs: `The band's placeholder look goes.`,
    shots: [['invite-settled-1600.png', 'invite-settled-1600.png', '✉️'], ['remove-settled-1600.png', 'remove-settled-1600.png', '❌']],
    options: [
      ['The sentences, both places', 'As built.'],
      ['The bracketed form, both places', 'Shorter; reads as a placeholder.'],
    ],
  },
  {
    title: 'No *last changed* line on a text clause\'s card',
    now: `A charter card says nothing about when its clause last changed; its history is its records' tabs.`,
    change: `Unchanged: no such line.`,
    buys: `No line on every judgment card that the reader is not asking for.`,
    costs: `When a clause last changed is a press away, on its record's tab.`,
    options: [
      ['No line', 'As today and as built.'],
      ['*Last changed · ‹when›*', 'A grey line on every charter card.'],
    ],
  },
  {
    title: 'The prototype\'s new words need a STYLE pass before they ship',
    now: `The proposal brought words that have not passed STYLE: the label vocabulary (*Current text*, *Current rule*, *Proposed*, *What you proposed*, *Previous text*, *Rival · 23%*, *Rejected proposal*), the reasons a button is dark (*Choose one first*, *Type an address first*, *One 🏛️ each — withdraw yours first*), *Undecided when the document closed*, the power clauses in the past tense, *You preferred this before it changed*, *Kept by the Founder at the start*. ⟨copy-check⟩ does not run on the prototype.`,
    change: `Whichever you choose, every one of these goes into ⟨design/copy.js⟩ before a member reads it.`,
    buys: `—`,
    costs: `—`,
    shots: [['quick-keys-closed-1600.png', 'quick-keys-closed-1600.png', '*Undecided when the document closed*']],
    options: [
      ['One STYLE pass before the build', 'The whole vocabulary passed and frozen into copy.js first, so every family lands with passed words.'],
      ['Family by family', 'Each stage\'s words pass STYLE as it lands.'],
      ['Accept the prototype\'s words', 'Into copy.js as they are.'],
    ],
  },
  {
    title: 'May your name and picture change after the document closes?',
    now: `On a closed document ✋ still offers ✓ *Save*. Nothing in SURFACE says whether your name and picture may change after the close; the diagnosis found it and could not call it a bug.`,
    change: `Depends on your answer; the prototype draws your row read-only on a closed document.`,
    buys: `—`,
    costs: `—`,
    shots: [['myname-closedband-1600.png', 'myname-closedband-1600.png', '✋ on the closed page']],
    options: [
      ['No — frozen with the record', 'The signatures stand under the names as they were; ✋ 🖼️ read-only after the close.'],
      ['Yes — how you appear is not the record', 'Name and picture stay editable; the record resolves names live, as people rows already do.'],
      ['Picture yes, name no', 'The name is what the signatures are under.'],
    ],
  },
];

export const findings = [
  {
    title: 'A member reads *Set to undefined* on 🌍 and ❌',
    now: `On a live document before 🍾, a member opening 🌍 in Rules (or ❌ under *Proposed for removal*) reads *Set to undefined*; the ❌ card also claims *Set by the founder when the document was made* for a price the document has not begun under. Plain bug 1: the value is looked up in the Founder's page state, which a member's page does not have.`,
    change: `The first line is the document's own sentence, so there is no second reader to print *undefined*; a check fails the build on *undefined*, *NaN*, *null* anywhere on a card.`,
    settles: `Settled by the grammar (one home per fact; 1541.14).`,
    stage: 3,
    shots: [['chamber-live_constitution_m-1-1600.png', null, '🌍 read by a member, today']],
  },
  {
    title: 'A closed document still asks you things and offers acts',
    now: `On a closed document the unaccepted grant offers *Accept ✒️* and its strip *Activate 🏛️*; ✉️ offers ✒️ *Send the invitations*; ✋ offers ✓ *Save*; every seat is served the admission card with *Prefer this* radios; ⏱️'s tabs say *waiting on you*; the topbar's ✏️ countdown still runs. Plain bugs 2 and 4.`,
    change: `Where the document is in its life is an input to every card, the tabs and the topbar: on a closed document nothing is offered but 🥂, no tab asks, the ✏️ countdown stops.`,
    settles: `Settled by the grammar (principle 4; the closed-page check).`,
    stage: 7,
    shots: [['grant-pen-live_closed_founder-1600.png', null, 'the ✒️ grant on a closed document, today'], ['topbar-closed-1600.png', null, 'the topbar on the closed page, today']],
  },
  {
    title: 'One card names two different choosers',
    now: `On the closed fixture's ⏱️ (and ⏰ on a live closing document) the card says *Chosen by the Founder ✒️*, then *Decided by the members.*, then its latest record *Changed by the Founder*. Plain bug 3: two functions decide the same fact by different rules.`,
    change: `One reader for who chose a rule, printed once.`,
    settles: `Settled by the grammar (one home per fact; 1541.5, 1541.14).`,
    stage: 3,
    shots: [['rate-closedband-1600.png', 'rate-closedband-1600.png', '⏱️ on the closed page']],
  },
  {
    title: 'The tab you press drops 33–99 px on every charter card, and the audit looks away',
    now: `*The tab you click does not move* holds in the band and fails on every charter card: the tab drops 33 px on a judgment, 62–84 on a record, 82 on a patch, 99 on the closed page's backlog at 390, because the label above the clause pushes it down. The card audit measures only the sideways half, with a comment calling the drop expected.`,
    change: `The label moves into the card's top space (1541.4); the audit measures both axes, on open, switch and close, at both widths.`,
    settles: `Settled by the grammar if 1541.4 is taken; the two-axis check is needed either way.`,
    stage: 6,
    shots: [['quick-keys-charter-1600.png', 'quick-keys-charter-1600.png', 'a quick judgment']],
  },
  {
    title: 'A dark button explains itself only in a tooltip, and ✉️\'s ✒️ is lit over an empty box',
    now: `100 cards' dark buttons say why only on hover — and a phone has no hover (🪶 settled: ✒️ ✏️ both dark, nothing says why). On ✉️ the Founder's ✒️ is lit over an empty address box, a button that changes nothing.`,
    change: `Each dark button's reason is visible text in the row (*Give it a name first*; two different reasons print one line each); a button over an empty required box is dark.`,
    settles: `Settled by the grammar (principles 5 and 8).`,
    stage: '3 onwards',
    shots: [['invite-seat_1-1600.png', 'invite-seat_1-1600.png', '✉️, a member']],
  },
  {
    title: 'The closed page does not say what the clock cut off, and claims powers in the present tense',
    now: `On the closed page 31 cards whose race or motion was still running show it with live-looking radios and nothing saying it was undecided at the close; 10 power cards say *The Founder may amend the title at will* on a document that has closed.`,
    change: `A cut-off race or motion says *Undecided when the document closed*, its proposals kept and labelled; a power reads *Until the document closed, the Founder could …*.`,
    settles: `Settled by the grammar (principle 4).`,
    stage: 7,
    shots: [['quick-keys-closed-1600.png', 'quick-keys-closed-1600.png', 'a judgment on the closed page'], ['pw_u_title-closedband-1600.png', 'pw_u_title-closedband-1600.png', 'a power card, closed']],
  },
  {
    title: 'An opened card covers the bottom of the line above it',
    now: `120 cards at 1600 (141 at 390) rise over the ink above their paragraph — at the founding ✉️'s card covers 10 px of the line above.`,
    change: `A card rises only into clear space (the cost is 1541.15).`,
    settles: `Settled by the grammar (the top-edge rule).`,
    stage: '3 and 6',
    shots: [['invite-founding-1600.png', 'invite-founding-1600.png', '✉️ at the founding']],
  },
  {
    title: 'Empty frames: a head box with nothing in it, and a button row drawn empty under its hairline',
    now: `About 322 opened cards carry an empty 24 px head box above everything; the closed page's text cards draw an empty button row under a hairline (24 cards — the held backlog item *the closed text cards' empty commit row*); 232 cards carry some empty part.`,
    change: `A part with nothing in it is not drawn and takes its hairline with it; hairlines only ever stand between two things.`,
    settles: `Settled by the grammar (presence and the hairline rule); the backlog item goes.`,
    stage: '1 onwards',
    shots: [['mo_mo-4-seat_1-1600.png', 'mo_mo-4-seat_1-1600.png', 'a motion card: the empty head box above the rule']],
  },
  {
    title: 'The mover\'s own motion card draws a radio with no label',
    now: `On a constitutional motion you moved, the rule as it stands carries an empty ring that does nothing; a screen reader hears an unnamed radio. Plain bug 7.`,
    change: `A radio exists only where the reader can choose; the mover's card has none, and its one button is *🗑️ Withdraw*.`,
    settles: `Settled by the grammar (a radio only on a live choice).`,
    stage: 4,
    shots: [['mo_mo-4-settled-1600.png', 'mo_mo-4-settled-1600.png', 'the mover\'s motion card']],
  },
  {
    title: 'The 👑 Text question\'s ✒️ is solid green, and its strip leads with 💡',
    now: `On a live document the Founder's 👑 question about the Text draws its ✒️ accept in solid green, and the strip's front tab is the race's 💡 rather than 👑. Plain bug 8.`,
    change: `✒️ drawn like every glyph button (1541.13); the strip's front tab is the card's own.`,
    settles: `The green is settled by the grammar; the front tab is a plain fix.`,
    stage: 4,
    shots: [['crown_cq-4-live_session_founder-1600.png', null, 'the 👑 Text question, today']],
  },
  {
    title: 'The floating proposal row overlaps a single-place draft\'s card',
    now: `In edit mode the floating 🗑️ ✏️ row covers the foot of a single-place draft's card (plain bug 9, its overlap half; which ✏️ survives is 1541.22).`,
    change: `The floating layer never covers a control or a line of text.`,
    settles: `Settled by the grammar (the overlay rule).`,
    stage: 8,
    shots: [['editing-one-site-1600.png', null, 'a single-place draft in edit mode, today']],
  },
  {
    title: 'On a phone, the contents drawer\'s marks run past its edge',
    now: `At 390 the lifecycle marks beside the contents drawer's headings run past the drawer's glass, and *…8 more* is cut. Plain bug 10.`,
    change: `The marks stay inside the drawer; a check asserts it at 390.`,
    settles: `A plain fix, guarded by the overlap check.`,
    stage: 8,
    shots: [['page-drawer-left-390.png', null, 'the contents drawer at 390, today']],
  },
  {
    title: 'Type and spacing off the scales',
    now: `23 font sizes and 67 spacing values in the stylesheets are off the type scale and the 4 px grid; every card box carries off-grid padding (the audit's S1 sees it 1,408 times).`,
    change: `Each on a token, or on an allow-list with its reason (the glyph size, the 24 px sockets); a style lint in CI.`,
    settles: `A check, not the grammar.`,
    stage: 1,
    shots: [],
  },
  {
    title: 'The fixture\'s closed page shows states a real closed document never has',
    now: `The fixture's closed page still serves 14 unjudged pairs, a park awaiting assent and an open ⏱️ motion — none of which a live closed document produces. The probes and the audits read the fixture, so they measure faults no member can meet (the only surviving orphan hairlines are here).`,
    change: `The fixture closes the way a live document does.`,
    settles: `A fixture fix.`,
    stage: 0,
    shots: [['park-accounts-closed-1600.png', 'park-accounts-closed-1600.png', 'the park on the fixture\'s closed page']],
  },
  {
    title: 'SURFACE\'s ordinary-motion row still says *Keep this*',
    now: `Q1377 changed *Keep* to *Prefer* on what stands, because the current rule is a peer of the proposal, and T48 says so; §9's ordinary-motion row still reads *Keep this*.`,
    change: `The row reads *Prefer this*, as the page already does.`,
    settles: `A SURFACE edit, scheduled with the motions stage.`,
    stage: 4,
    shots: [['mo_mo-5-settled-1600.png', 'mo_mo-5-settled-1600.png', 'an ordinary motion']],
  },
];

export const findingOptions = [
  ['Fix it in the build', 'In the BUILD.md stage named, with its check.'],
  ['Fix it now', 'A small patch on main before the build starts.'],
  ['Leave it', 'Veto: it is not a fault, or not worth fixing.'],
];

// Backlog 1541's held items, judged against the grammar.
export const backlog = [
  ['*Set to / Set by* on every read-only setting card', 'Settled by the grammar — one home per fact; answered through **1541.14**. Drop it from the backlog.'],
  ['The closed text cards\' empty commit row (P12\'s 24)', 'Settled by the grammar — a part with nothing in it is not drawn, and a closed card has no job; finding **1541.36**. Drop it.'],
  ['🗑️ alone against §9.1\'s close-only OK', 'Settled by the grammar — neither survives: no lone 🗑️ (**1541.9**) and no close-only OK (**1541.8**). Drop it; your answer to 1541.8 is the ruling.'],
  ['The separate cross-width design offer', 'Read as the offer to design the phone separately; the grammar answers *one design, folded* (the same zones, 0 px on open at both widths). The one open choice is **1541.20**, which carries this item. If the offer meant something else, say so there.'],
  ['The ten plain bugs', '1 → **1541.29**; 2 and 4 → **1541.30**; 3 → **1541.31**; 5 → **1541.23**; 6 → **1541.17**; 7 → **1541.37**; 8 → **1541.38**; 9 → **1541.22** and **1541.39**; 10 → **1541.40**. The eleventh (CLAUDE.md\'s heading ladder) was fixed on main in 178e0e99.'],
];

// The five §6 cards and one representative pair per family, for the review's gallery.
export const lead = [
  ['title-settled', '🪶 Title, settled, read by the Founder'],
  ['quick-keys-charter', 'A quick judgment (💡), a member'],
  ['race-claims-charter', 'A sealed record (✔)'],
  ['mo_mo-4-seat_1', 'A constitutional motion (👤), a member who is not the mover'],
  ['invite-seat_1', '✉️ Invite, a member, at the all-members price'],
];

export const families = [
  ['Judgment — quick, closed page', 'quick-keys-closed'],
  ['Judgment — insertion at a gap', 'insert-quiet-charter'],
  ['Judgment — a race of rivals', 'race-purse-charter'],
  ['Judgment — a pair you judged (⏳)', 'quick-guests-count-charter'],
  ['Judgment — a patch over several places', 'patch-rename-charter'],
  ['Judgment — the deadlock (⚔️)', 'race-sanctions-charter'],
  ['Your own proposal', 'mine-guests-wording-charter'],
  ['Your proposal, stranded', 'mine-lostkey-stranded-charter'],
  ['Sealed record, closed page', 'race-claims-closed'],
  ['The backlog, closed page', 'rec_fx-u0-closed'],
  ['Settled motion record', 'rec_chamber_0-settled'],
  ['A setting at the founding', 'rate-founding'],
  ['A setting, settled', 'chamber-settled'],
  ['A setting, closed page', 'rate-closedband'],
  ['🪶 at the birth', 'title-founding'],
  ['🪪 Admissions', 'admission-settled'],
  ['🤝 Applications', 'applications-settled'],
  ['🎩 Founder\'s membership', 'hat-settled'],
  ['🎩 on the closed page', 'hat-closedband'],
  ['A blind answer', 'ans-chamber-answers'],
  ['A power card (✒️)', 'pw_u_title-settled'],
  ['A power card, closed', 'pw_u_title-closedband'],
  ['Constitutional motion, the mover', 'mo_mo-4-settled'],
  ['Ordinary motion', 'mo_mo-5-settled'],
  ['👑 question', 'mo_mo-3-settled'],
  ['👑 read by the mover', 'mo_mo-3-seat_1'],
  ['Park (⏳)', 'park-accounts-charter'],
  ['Failed-motion news', 'held_mo-2-seat_1'],
  ['A grant (🏛️)', 'grant-voice-founding'],
  ['A grant, accepted (✒️)', 'grant-pen-settled'],
  ['A gate (💡)', 'canpropose-settled'],
  ['News of a change, read by a member', 'chamber-seat_1'],
  ['🍾 Begin, settled', 'begin-settled'],
  ['🥂 Closing', 'closing-closedband'],
  ['✉️ Invite, the Founder', 'invite-settled'],
  ['❌ Remove', 'remove-settled'],
  ['🌂 Leave', 'leave-settled'],
  ['The stranger\'s card (📧)', 'strlogin-seat_stranger'],
  ['✋ Your name', 'myname-founding'],
  ['🖼️ Your picture', 'mypic-founding'],
  ['✋ on the closed page', 'myname-closedband'],
];
